### ISSUE TITLE
Digital pin addresses and project status

### ISSUE THREAD

**Issue by SimonRZz** [MaineTim/8266_remote_keyer#1]
Hi Tim,

I'm looking for a way to remotely key my IC-705 and came across your project. I tried to compile your code but getting a lot of compilation errors. I changed the digital pin addresses to:

// PINS

const int pinSetup = 13;               // Press Setup (Adjust speed and tone)
const int pinKeyDit = 14;              // Key, dit paddle
const int pinKeyDah = 12;              // Key, dah paddle
const int pinStatusLed = 2;           // Led ESP8266 builin
const int pinMosfet = 16;              // Key rig jack
const int pinSpeaker = 15;             // Speaker

but the list of compilation errors continues... 

Are you actively using your code/project and or have you had a chance to work on this lately? 

73! Simon

**Comment by MaineTim** [comment]
Hi Simon,

Sorry for the slow response. I'm not currently operating remotely, and the computer with the development environment for this project isn't immediately accessible to me. If you want, post the compiler output and let's take a look.

73 - Tim

**Comment by SimonRZz** [comment]
Thanks Tim, now I have to apologize!
I have now gotten the code to work with Visual Studio Code (previously I had tried it with Arduino IDE). It's working just fine. Thanks & 73!
Simon
